name: Meta Check
on: pull_request

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeNA/unity-meta-check@v3
        with:
          target_path: Pong-Pong
